spring:
  profiles:
    default: local

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

application:
  title: Rewards Points API
  version: 0.0.1
